version: '3.8'

services:
  database:
    image: postgres:17.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pass
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

volumes:
  db_volume:

networks:
  app-network:
    driver: bridge