server:
  port: 8080

jwt:
  secret: 77d26d45-b221-4555-908b-3e7b6fda166ba13SQQ-W
  lifetime: 10m


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tasks
    username: postgres
    password: pass

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5433/tasks
    user: postgres
    password: pass
    enabled: true
    default-schema: public





